{ config, pkgs, ... }:

{
  # 平板代理自动切换 - 使用可写入的配置文件

  # 1. NetworkManager dispatcher 脚本
  environment.etc."NetworkManager/dispatcher.d/99-tablet-proxy" = {
    source = pkgs.writeShellScript "tablet-proxy-dispatcher" ''
      INTERFACE="$1"
      ACTION="$2"
      TABLET_IP="192.168.80.242"
      TABLET_PROXY_PORT="7890"
      LOCAL_PROXY="http://127.0.0.1:7890"
      TABLET_PROXY="http://$TABLET_IP:$TABLET_PROXY_PORT"

      # 使用可写入的配置文件（不在 /etc 下）
      PROXY_ENV_FILE="/var/lib/tablet-proxy/current.sh"
      PROXY_LINK="/etc/profile.d/zzz-tablet-proxy.sh"

      log() {
          echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> /var/log/tablet-proxy.log
      }

      check_tablet_proxy() {
          ${pkgs.netcat}/bin/nc -zw3 "$TABLET_IP" "$TABLET_PROXY_PORT" 2>/dev/null
      }

      enable_tablet_proxy() {
          log "启用平板代理: $TABLET_PROXY"
          cat > "$PROXY_ENV_FILE" <<EOF
      # Auto-generated by tablet-proxy-dispatcher
      # 平板代理优先
      export http_proxy="$TABLET_PROXY"
      export https_proxy="$TABLET_PROXY"
      export HTTP_PROXY="$TABLET_PROXY"
      export HTTPS_PROXY="$TABLET_PROXY"
      export no_proxy="127.0.0.0/8,192.168.0.0/16,10.0.0.0/8,localhost,*.local,open.bigmodel.cn"
      export NO_PROXY="127.0.0.0/8,192.168.0.0/16,10.0.0.0/8,localhost,*.local,open.bigmodel.cn"
      EOF
          # 通知桌面环境重新加载环境变量（KDE）
          ${pkgs.systemd}/bin/systemctl --user restart plasma-ksystemstats.service 2>/dev/null || true
          ${pkgs.libnotify}/bin/notify-send "代理切换" "已切换到平板代理 $TABLET_IP" -u low 2>/dev/null || true
      }

      enable_local_proxy() {
          log "恢复本地代理: $LOCAL_PROXY"
          cat > "$PROXY_ENV_FILE" <<EOF
      # Auto-generated by tablet-proxy-dispatcher
      # 本地代理
      export http_proxy="$LOCAL_PROXY"
      export https_proxy="$LOCAL_PROXY"
      export HTTP_PROXY="$LOCAL_PROXY"
      export HTTPS_PROXY="$LOCAL_PROXY"
      export no_proxy="127.0.0.0/8,192.168.0.0/16,10.0.0.0/8,localhost,*.local,open.bigmodel.cn"
      export NO_PROXY="127.0.0.0/8,192.168.0.0/16,10.0.0.0/8,localhost,*.local,open.bigmodel.cn"
      EOF
          ${pkgs.libnotify}/bin/notify-send "代理切换" "已恢复本地代理" -u low 2>/dev/null || true
      }

      case "$ACTION" in
          up)
              # 严格匹配 USB 以太网接口（enp 开头 + u 在中间 + 数字结尾）
              # 避免误匹配 WiFi 接口（wlp0s20f0u9）
              if [[ "$INTERFACE" =~ ^enp.*u[0-9]+$ ]]; then
                  log "检测到 USB 网络接口: $INTERFACE"
                  sleep 2
                  if check_tablet_proxy; then
                      enable_tablet_proxy
                  else
                      log "平板网络接口 $INTERFACE 启动，但代理不可达"
                  fi
              fi
              ;;
          down)
              if [[ "$INTERFACE" =~ ^enp.*u[0-9]+$ ]]; then
                  log "USB 网络接口 $INTERFACE 断开"
                  if ! check_tablet_proxy; then
                      enable_local_proxy
                  fi
              fi
              ;;
      esac
    '';
    mode = "0755";
  };

  # 2. 创建符号链接，让 shell 自动加载代理配置
  environment.etc."profile.d/zzz-tablet-proxy.sh" = {
    source = "/var/lib/tablet-proxy/current.sh";
  };

  # 3. 初始化配置文件目录和默认配置
  systemd.tmpfiles.rules = [
    "d /var/lib/tablet-proxy 0755 root root -"
    "f /var/log/tablet-proxy.log 0644 root root -"
  ];

  # 4. 启动时创建默认配置（本地代理）
  system.activationScripts.tabletProxyInit = ''
    if [ ! -f /var/lib/tablet-proxy/current.sh ]; then
      cat > /var/lib/tablet-proxy/current.sh <<'EOF'
# Default local proxy configuration
export http_proxy="http://127.0.0.1:7890"
export https_proxy="http://127.0.0.1:7890"
export HTTP_PROXY="http://127.0.0.1:7890"
export HTTPS_PROXY="http://127.0.0.1:7890"
export no_proxy="127.0.0.0/8,192.168.0.0/16,10.0.0.0/8,localhost,*.local,open.bigmodel.cn"
export NO_PROXY="127.0.0.0/8,192.168.0.0/16,10.0.0.0/8,localhost,*.local,open.bigmodel.cn"
EOF
    fi
  '';

  # 5. 手动切换命令（可选）
  environment.systemPackages = [
    (pkgs.writeShellScriptBin "proxy-switch" ''
      # 手动切换代理工具
      case "$1" in
        tablet)
          cat > /var/lib/tablet-proxy/current.sh <<'EOF'
export http_proxy="http://192.168.80.242:7890"
export https_proxy="http://192.168.80.242:7890"
export HTTP_PROXY="http://192.168.80.242:7890"
export HTTPS_PROXY="http://192.168.80.242:7890"
export no_proxy="127.0.0.0/8,192.168.0.0/16,10.0.0.0/8,localhost,*.local,open.bigmodel.cn"
export NO_PROXY="127.0.0.0/8,192.168.0.0/16,10.0.0.0/8,localhost,*.local,open.bigmodel.cn"
EOF
          echo "已切换到平板代理（重启 shell 生效）"
          ;;
        local)
          cat > /var/lib/tablet-proxy/current.sh <<'EOF'
export http_proxy="http://127.0.0.1:7890"
export https_proxy="http://127.0.0.1:7890"
export HTTP_PROXY="http://127.0.0.1:7890"
export HTTPS_PROXY="http://127.0.0.1:7890"
export no_proxy="127.0.0.0/8,192.168.0.0/16,10.0.0.0/8,localhost,*.local,open.bigmodel.cn"
export NO_PROXY="127.0.0.0/8,192.168.0.0/16,10.0.0.0/8,localhost,*.local,open.bigmodel.cn"
EOF
          echo "已切换到本地代理（重启 shell 生效）"
          ;;
        status)
          echo "当前代理配置:"
          grep "export http_proxy" /var/lib/tablet-proxy/current.sh 2>/dev/null || echo "配置文件不存在"
          echo ""
          echo "实际环境变量:"
          env | grep -i proxy | grep -v SOPS
          ;;
        *)
          echo "用法: proxy-switch [tablet|local|status]"
          echo "  tablet - 切换到平板代理"
          echo "  local  - 切换到本地代理"
          echo "  status - 查看当前状态"
          ;;
      esac
    '')
  ];
}
